"""R149: appends the Ash Tomato's three growth variations (gen_ash_tomato_variants.luau) to ApprovedPlantArt5, after the base commit's
own design, which stays byte for byte as it is (the module only gains a comment line and three more designs).
Usage: python3 gen_ash_tomato_variants.py <variants.txt> <base src dir> <out src dir>"""
import os, sys

rows, base_src, out_src = sys.argv[1:4]
variants = []
for line in open(rows, encoding='utf-8'):
    if line.startswith('VARIANT\t'):
        variants.append(line.rstrip('\n').split('\t', 2)[2])
assert len(variants) == 3, 'three variants expected'
path = os.path.join(base_src, 'ReplicatedStorage', 'ApprovedPlantArt5.lua')
text = open(path, encoding='utf-8').read()
assert text.startswith('return {{') and text.rstrip().endswith('}}')
body = text.rstrip()[:-1]  # drop the outer closing brace
header = ('-- R149 (owner: Ash Tomato keeps its look, plus growth variations): design 1 is the Ash Tomato exactly as it was; designs 2-4 are\n'
          '-- variations of it (mirror / size / lean, leaf swing and a few leaves fewer, each tomato scaled and twisted about its socket, a shade of\n'
          '-- red and of green), generated by docs/proposals/R149/tools/gen_ash_tomato_variants.luau. ApprovedPlantArt.Get picks one per crop from a\n'
          '-- hash of its id (ApprovedPlantArt.Key tells them apart); every design has the same 4 fruit.\n')
out = header + body + ',' + ','.join(variants) + '}\n'
open(os.path.join(out_src, 'ReplicatedStorage', 'ApprovedPlantArt5.lua'), 'w', encoding='utf-8', newline='').write(out)
print('wrote ApprovedPlantArt5.lua with', 1 + len(variants), 'designs')
