"""R149: appends the Ash Tomato's three growth variations (gen_ash_tomato_variants.luau) to ApprovedPlantArt5, after the base commit's
own design, which stays as it is except for ONE touch-up (review part 2, finding 5): the 12 "Flat ash patch" blocks (3 on each tomato) are
.02 thicker and their centres .01 higher along their own up axis, so a patch's top no longer lies .013 over its tomato's top (z-fighting
in the zfight detector: near-coplanar). The bottom of a patch stays where it was (inside the tomato). The variations get the same touch-up
in gen_ash_tomato_variants.luau, scaled by their design scale. Nothing else in design 1 changes: the module gains a comment line and three more
designs.
Usage: python3 gen_ash_tomato_variants.py <variants.txt> <base src dir> <out src dir>"""
import os, re, sys
from decimal import Decimal

PATCH_THICKER, PATCH_HIGHER = Decimal('0.02'), Decimal('0.01')
# one spec literal of a "Flat ash patch" (the file's own field order: z, c, t, m, g, k, f ...)
PATCH = re.compile(r'(\{\["z"\]=\{)([^}]*)(\},\["c"\]=\{)([^}]*)(\},\["t"\]=\d+,\["m"\]="[^"]*",\["g"\]=\d+,\["k"\]=\{[^}]*\},\["f"\]="Flat ash patch")')


def touch_up(match):
    z = match.group(2).split(',')
    c = match.group(4).split(',')
    up = (Decimal(c[4]), Decimal(c[7]), Decimal(c[10]))  # column 2 of the row-major rotation c[3..11] = the patch's own up axis
    assert up == (0, 1, 0), 'a design-1 patch is expected to stand level (yaw only), got up axis %s' % (up,)
    z[1] = str(Decimal(z[1]) + PATCH_THICKER)
    c[1] = str(Decimal(c[1]) + PATCH_HIGHER)
    return match.group(1) + ','.join(z) + match.group(3) + ','.join(c) + match.group(5)

rows, base_src, out_src = sys.argv[1:4]
variants = []
for line in open(rows, encoding='utf-8'):
    if line.startswith('VARIANT\t'):
        variants.append(line.rstrip('\n').split('\t', 2)[2])
assert len(variants) == 3, 'three variants expected'
path = os.path.join(base_src, 'ReplicatedStorage', 'ApprovedPlantArt5.lua')
text = open(path, encoding='utf-8').read()
assert text.startswith('return {{') and text.rstrip().endswith('}}')
body = text.rstrip()[:-1]  # drop the outer closing brace
body, patches = PATCH.subn(touch_up, body)
assert patches == 12, 'twelve flat ash patches expected in design 1 (3 on each of the 4 tomatoes), found %d' % patches
header = ('-- R149 (owner: Ash Tomato keeps its look, plus growth variations): design 1 is the Ash Tomato as it was (its 12 flat ash patches are .02 thicker\n'
          '-- and .01 higher: no z-fighting with the tomato top, review part 2); designs 2-4 are\n'
          '-- variations of it (mirror / size / lean, leaf swing and a few leaves fewer, each tomato scaled and twisted about its socket, a shade of\n'
          '-- red and of green), generated by docs/proposals/R149/tools/gen_ash_tomato_variants.luau. ApprovedPlantArt.Get picks one per crop from a\n'
          '-- hash of its id (ApprovedPlantArt.Key tells them apart); every design has the same 4 fruit.\n')
out = header + body + ',' + ','.join(variants) + '}\n'
open(os.path.join(out_src, 'ReplicatedStorage', 'ApprovedPlantArt5.lua'), 'w', encoding='utf-8', newline='').write(out)
print('wrote ApprovedPlantArt5.lua with', 1 + len(variants), 'designs;', patches, 'flat ash patches of design 1 touched up')
