#!/bin/sh
# Usage: sh run_packs.sh [scratch dir] [--mutations] [--suites] [--base REF]
# R151 pack-models audit (owner: "look into refining and loosing the packs that we currently have; ensure there aren't any dislocated parts; the packs
# are all using the same mesh and shape and so on; make sure everything is connected for the packs") on the Roblox mock (/opt/luau/luau) with the REAL
# modules / scripts of this checkout and the REAL pack templates of the owner's place (pack_templates.luau, generated by tools/gen_pack_templates.py
# from the place file: 42 designs, 115 MeshParts; the meshes' vertices are uploaded assets and not available offline: every MeshPart is its Size box).
#  1. test_packs.luau        every pack the game can build (78 stage x variant combinations x 5 sizes x 3 coats; ground, held R15 + R6, picture, opening copy,
#                            market, mystery, viewport, pad) - registry, structure, connection (welds / motors, 120 simulated frames of a running carrier,
#                            the REAL SeedPackRender hovering the anchored ones), the same pack in every context, giants, weather, pads, special packs.
#  2. dump_packs.luau + check_packs.py   the geometry of every distinct design (42 + Void + Mech + Verity + the 7 pads): FLOATING parts (every part touches
#                            the body through touching parts) and Z-FIGHTING (tools/zfight.py; mesh-box pairs are listed, not counted).
#  3. fingerprint_packs.luau + compare_fingerprints.py   BEFORE (the base commit, default b196944 = the R151 pack audit as merged) against AFTER: every
#                            property of every part of 1,500+ packs; NOTHING may differ (the Verity pouch work changes no other pack, and with no baked pouch
#                            the Verity pack is the unchanged R149 sachet). `--base c1e8829` (R150 + the research) reproduces the audit's own three fixes.
#  4. run_verity_pouch.sh    (R151 follow-up: the Verity pack is the REAL chip-bag pouch in pure yellow, baked at runtime; the sachet is the fallback) - the
#                            EditableMesh bake on a mock with a switch for every failure, the pouch pack in every context, the sachet fallback, no leaks,
#                            and every other pack identical with the pouch ready and without it.
#  5. run_pack_shapes.sh     (R151 follow-up: chip-bag shape variations designed in Blender, applied at run time to the owner's own pouch meshes) - the field against
#                            the Blender design's samples, one fixed variation per design name, the EditableMesh bake (every vertex moved, y and the crimps exactly
#                            where they were, <= 5% outward, colours / UVs kept), every context identical, the fallbacks, the switches and /test packshape.
#  --mutations   breaks the pack code 13 ways (an unwelded strip, an anchored held part, an unwelded root, the giant tags, a wrong PackLocalFrame, a size
#                jump between contexts, a part count, a Mech motor, a floating seal, a z-fighting duplicate, a weather part, an unwelded Verity block, a
#                Void star off the face) and expects the audit to notice each one.
#  --suites      also runs the existing suites that touch packs (R149 / R147 Verity pack, R147 Verity art / UI, veiled R122, R137, R138, R148 index / purchase /
#                roster, R150, R149 run_all) and prints their counts.
set -e
HERE=$(cd "$(dirname "$0")" && pwd);REPO=$(cd "$HERE/../../../.." && pwd)
OUT=$(mktemp -d);BASE=${PACKS_BASE:-b196944};MUT=0;SUITES=0
if [ -n "$1" ] && [ "${1#--}" = "$1" ];then OUT=$1;shift;fi
mkdir -p "$OUT"
while [ $# -gt 0 ];do case "$1" in --mutations) MUT=1;; --suites) SUITES=1;; --base) shift;BASE=$1;; esac;shift;done
T=$REPO/tools/tests;INV=$REPO/docs/proposals/inventory_R113/tests
LUAU=${LUAU:-/opt/luau/luau}
stage() { # $1 = dir
 mkdir -p "$1"
 cp "$T/roblox.luau" "$INV/world.luau" "$INV/fixtures.luau" "$HERE/pack_world.luau" "$HERE/pack_templates.luau" "$HERE/test_packs.luau" "$HERE/dump_packs.luau" "$HERE/fingerprint_packs.luau" "$1/"
}
bundle() { python3 "$HERE/mkbundle_packs.py" "$1" "$2" >/dev/null; } # $1 = out dir, $2 = src dir

echo "== test_packs (this checkout)"
stage "$OUT/after";bundle "$OUT/after" "$REPO/src"
(cd "$OUT/after" && timeout 900 $LUAU test_packs.luau > test_packs.log 2>&1) || { grep -v '^WARN' "$OUT/after/test_packs.log" | tail -40;exit 1; }
grep -v '^WARN' "$OUT/after/test_packs.log" | grep -E "^(structure|contexts|giants|weather|pads|designs|[0-9]+ checks)"

echo "== geometry: floating parts and z-fighting (check_packs.py on the 42 designs + Void + Mech + Verity + 7 pads)"
(cd "$OUT/after" && timeout 600 $LUAU dump_packs.luau > scenes.txt 2>&1)
python3 "$HERE/check_packs.py" "$OUT/after/scenes.txt"

echo "== before / after: every part of every pack, base $BASE against this checkout"
mkdir -p "$OUT/base_src"
git -C "$REPO" archive "$BASE" src | tar -x -C "$OUT/base_src"
stage "$OUT/before";bundle "$OUT/before" "$OUT/base_src/src"
(cd "$OUT/before" && timeout 900 $LUAU fingerprint_packs.luau > fp.txt 2>&1) &
(cd "$OUT/after" && timeout 900 $LUAU fingerprint_packs.luau > fp.txt 2>&1)
wait
grep '^COUNT' "$OUT/before/fp.txt" "$OUT/after/fp.txt"
# against the audit's merge nothing may differ. Against the pre-audit base only the audit's documented fixes may: the giant tags on the seal / tear strips
# (SeedPackVisuals), the Void's stars / specks / rune strokes backed onto the pouch (EclipsePackArt) and the moss patches / ice glaze of the pads made .006 thicker
# (SeedPackVisuals.Platform)
if [ "$BASE" = "c1e8829" ];then
 python3 "$HERE/compare_fingerprints.py" "$OUT/before/fp.txt" "$OUT/after/fp.txt" --expect-only '^Part (BottomSeal|TearStripN): tags' '^Part (StarV|StarH|StarSpeck)[FB]N: ' '^Part RuneSigil[FB]N_N: ' '^Part (MossPatch|IceGlaze): size  \[pad\]'
else
 python3 "$HERE/compare_fingerprints.py" "$OUT/before/fp.txt" "$OUT/after/fp.txt" --expect-only '(?!)'
fi

echo "== the Verity pouch (VerityPouch151): runtime bake, pouch pack, sachet fallback"
if [ "$MUT" = 1 ];then sh "$HERE/run_verity_pouch.sh" "$OUT/pouch" --mutations;else sh "$HERE/run_verity_pouch.sh" "$OUT/pouch";fi

echo "== the pack shape variations (PackShapes151): the Blender field, the run-time bake, every context, the fallbacks, the switches"
if [ "$MUT" = 1 ];then sh "$HERE/run_pack_shapes.sh" "$OUT/shapes" --mutations;else sh "$HERE/run_pack_shapes.sh" "$OUT/shapes";fi

if [ "$MUT" = 1 ];then
 echo "== mutations: the audit must notice each broken copy of the pack code"
 for m in $(python3 "$HERE/mutate_packs.py" x list);do
  rm -rf "$OUT/mut";mkdir -p "$OUT/mut";cp -r "$REPO/src" "$OUT/mut/src"
  expect=$(python3 "$HERE/mutate_packs.py" "$OUT/mut/src" "$m")
  stage "$OUT/mut/run";bundle "$OUT/mut/run" "$OUT/mut/src";echo 'return true' > "$OUT/mut/run/quick_mode.luau"
  noticed=0
  case "$expect" in
   test:*) kind=${expect#test:}
    (cd "$OUT/mut/run" && timeout 600 $LUAU test_packs.luau > t.log 2>&1) && noticed=0 || { if grep -q "failures by kind:.*$kind=" "$OUT/mut/run/t.log";then noticed=1;fi; };;
   geometry)
    (cd "$OUT/mut/run" && timeout 600 $LUAU dump_packs.luau > scenes.txt 2>&1) && python3 "$HERE/check_packs.py" "$OUT/mut/run/scenes.txt" --quiet >/dev/null && noticed=0 || noticed=1;;
  esac
  if [ "$noticed" = 1 ];then echo "ok: mutant $m noticed ($expect)";else echo "FAIL: mutant $m was NOT noticed ($expect)";exit 1;fi
 done
fi

if [ "$SUITES" = 1 ];then
 echo "== existing pack suites"
 P=$REPO/docs/proposals
 for s in "R149 Verity pack:$P/R149/tests/run_verity_pack.sh" "R147 Verity pack:$P/R147/tests/run_verity_pack.sh" "R147 Verity art:$P/R147/tests/run_verity_art.sh" \
          "veiled R122:$P/veiled_R122/tests/run.sh" "R137:$P/R137/tests/run.sh" "R138:$P/R138/tests/run.sh" "R148 index limited:$P/R148/tests/run_index_limited.sh" \
"R147 Verity UI:$P/R147/tests/run_verity_ui.sh" "R148 purchase:$P/R148/tests/run_purchase.sh" "R148 roster:$P/R148/tests/run_roster.sh" "R150:$P/R150/tests/run_all.sh" "R149 run_all:$P/R149/tests/run_all.sh";do
  label=${s%%:*};script=${s#*:}
  dir=$OUT/suite_$(echo "$label" | tr ' ' '_')
  if sh "$script" "$dir" > "$dir.log" 2>&1;then echo "ok:   $label ($(grep -E '[0-9]+ checks, [0-9]+ failures|checks [0-9]+, fails|ALL PASS|suites passed' "$dir.log" | tr '\n' ';' | cut -c1-200))";else echo "FAIL: $label";tail -20 "$dir.log";exit 1;fi
 done
fi
echo "all pack checks passed"
