-- R123: owner/admin command list for the F4 panel and /test help. Grouped by area; one row per command.
-- Works in Studio and in public servers for the owner and AdminUserIds. Add @username, @me or @all at the end
-- to run a player command on someone else (rows marked "server" affect the whole server and take no @target).
return {
 {'HOW IT WORKS','Type in chat as /test <command> or open F4 / TOOLS. Add @username or @all at the end for other players. Saved changes: inventory, cash, gems, speed, treadmill, boots, trails, fence. Temporary: fly, noclip, movespeed, animrate.'},
 {'/test admins','server: Show who can use these commands (owner + AdminUserIds) and who in this server has access.'},

 {'— PLAYER —',''},
 {'/test stats @username','Seeds, packs, plants, harvests, cash and speed points.'},
 {'/test cash set 1000000 @username','Set cash. cash add <amount> adds instead.'},
 {'/test gems add 100 @username','Add Gems (gems set also works).'},
 {'/test speed 100000000000 @username','Set saved speed points (points, not studs per second).'},
 {'/test treadmill 7 @username','Set treadmill tier 1–7 (Forest … Storm).'},
 {'/test boots 5 @username','Unlock and equip luck boots 1–5.'},
 {'/test trail 6 @username','Unlock and equip training trail 1–6.'},
 {'/test fence 7 @username','Set fence tier 1–7.'},
 {'/test bundle SpeedSmall @username','Grant a shop bundle with no purchase. Cash/CashSmall/CashMedium/CashValue/CashMega, same for Speed.'},
 {'/test training @username','Treadmill gain per second, multiplier and physical speed.'},
 {'/test gardenbonus @username','Garden size and growth-time bonuses.'},
 {'/test cashoffers @username','Cash bundle amounts for this player. No purchase.'},

 {'— MOVEMENT —',''},
 {'/test fly 100 @username','Fly (WASD, Space/E up, Ctrl/Q down). unfly stops.'},
 {'/test noclip @username','Walk through walls. clip restores.'},
 {'/test movespeed 300 @username','Temporary walk speed 24–500. movespeed off restores.'},
 {'/test animrate 2.5 @username','Temporary run animation speed. animrate off restores.'},
 {'/test base @username','Teleport home.'},
 {'/test tp storm @username','Teleport to a biome: forest, jungle, desert, snow, lava, crystal, storm.'},
 {'/test heal @username','Restore health. respawn respawns.'},

 {'— PACKS & SEEDS —',''},
 {'/test packset storm @username','One pack of each tier from a biome.'},
 {'/test pack storm 6 @username','One pack: biome, tier 1–6, then optional size, none/gold/diamond, count.'},
 {'/test void 1 @username','Void Pack(s) 1–20 (Secret-or-better odds, 1/200 Mech).'},
 {'/test verity 1 @username','Verity Pack(s) 1–20 (Verity seed 1/100, then Secret / Cosmic without the King seeds, 1/200 Mech without the Crowncore Tree). Verity also swaps a Void Pack you hand in for one.'},
 {'/test rarepacks @username','Five TEST packs that reveal Legendary, Mythic, Secret, Cosmic and King. rarepacks mech gives the six Mech designs; rarepacks king just one; rarepacks verity a TEST Verity Pack that reveals the Verity seed; rarepacks roster four TEST packs that reveal Fire Pepper, Moon Melon, Aloe and Sand Fruit.'},
 {'/test rarepull king @username','R151: play a pull reveal with a demo seed (nothing granted): secret / cosmic / king story scenes, or common..mythic.'},
 {'/test raresound KingFanfare @username','R151: play one pull sound slot alone (RarePullSounds) to audition an uploaded id.'},
 {'/test seeds snow @username','All seeds of a biome (seeds all = every seed, seeds verity = the Verity seed).'},
 {'/test seed <SeedId> @username','One seed by id (see catalog). Or type: give big diamond apple seed to @username.'},
 {'/test catalog storm','List seed ids, biomes and rarities.'},
 {'/test odds storm mythic 1','Real per-seed odds for a biome + tier + luck. odds event = Void Pack odds, odds verity = Verity Pack odds.'},
 {'/test indexinfo storm @username','Index reward status. claimindex claims it the normal way.'},
 {'take apple seeds from @username','Remove matching seeds (seed = one, seeds = all).'},

 {'— GARDEN —',''},
 {'/test plants all @username','Plant mature examples of every crop (plant <SeedId> for one).'},
 {'/test growall @username','Finish growing now. growth 0–100 sets the stage; growtime 30 restarts with a 30 s timer.'},
 {'/test regrow @username','Make fruit ready again on mature plants.'},
 {'/test harvestall @username','Pick all ready fruit that fits the bag.'},
 {'/test sellall @username','Sell all harvested fruit.'},
 {'/test fruithour ember pumpkin 3','server: Make a fruit the Fruit of the Hour (x1.5–3) for 10 minutes. fruithour off goes back to the clock.'},
 {'/test clear inventory @username','Clear seeds, packs and fruit (keeps the shovel). Also: seeds, packs, plants, harvests, all.'},
 {'/test clearinventory all','server: Clear everyone’s inventory. cleargarden all clears everyone’s garden.'},

 {'— TRACK, KEEPERS & EVENTS —',''},
 {'/test refreshpacks','server: Run the normal track refresh now.'},
 {'/test refreshcycle 30','server: Refresh into reset 30 (Legendary every 5, Mythic every 10, The Darkened every 3).'},
 {'/test pity 30','Preview what reset 30 guarantees. spawnodds shows normal slot chances.'},
 {'/test mystery @username','R141 base mystery pack. ready = unlocks in 3 s, next = pretend a new day, reset.'},
 {'/test daily @username','R140 login week + daily quests. next = pretend a new day, done = finish today\'s quests, week = next claim is day 7 (Mech pack), reset.'},
 {'/test plantnotify','R151 offline "your plant is ready" notifier: setup check + queue + your cooldown. send = send you one now (Roblox: 1 a day), reset = clear your cooldown.'},
 {'/test packluck @username 29','Hidden big-pack luck (players never see it). 29 makes their next earned pack 5x+.'},
 {'/test routes','Biome lengths and keeper speeds.'},
 {'/test fling storm @username','Fling like a keeper (forest … storm, or darkened). Tests air time; nothing drops.'},
 {'/test ragdoll 4 @username','Ragdoll for 0.5–10 s, like falling in a hole.'},
 {'/test weather thunder','server: Weather clear, rain, thunder or blizzard. Add all (rain all) to change every pack/plant/fruit.'},
 {'/test event spawn','server: Spawn The Darkened and its two Void Packs. event clear removes them.'},
 {'/test event status','server: The Darkened’s state, packs left and unstolen refreshes (reroll at 3).'},
 {'/test event go @username','Teleport next to a Void Pack.'},
 {'/test eventpack 7.5 diamond','server: Change the size/material of the waiting Void Pack.'},
 {'/test keepersmack','server: Preview The Darkened’s smack pose (hits nobody).'},
 {'/test notice event @username','Preview a notice: event, legendary, mythic or giant. Spawns nothing.'},

 {'— SHOVEL HOLES —',''},
 {'/test holes','server: List holes on the track per player. holes clear removes them all.'},
 {'/test dig @username','Dig a hole at the target’s feet, skipping the cooldown (they must hold the shovel on the track; the 4-hole limit still applies).'},

 {'— TREADMILL BONUS —',''},
 {'/test bonus @username','Ready rolls, saved progress toward the next one, and which biomes are in their roll pool.'},
 {'/test bonus ready 2 @username','Set 0–2 ready rolls (the roll button appears). Leaving the game loses them.'},
 {'/test bonus progress 5:50 @username','Set saved treadmill time (seconds or m:ss, max 6:00). 5:50 = roll in 10 s on the treadmill.'},
 {'/test bonus roll @username','Use a ready roll for them now (grants the pack, no animation).'},
 {'— PULL ANNOUNCEMENTS —',''},
 {'/test announce <seed> @username','R151: the chat line for everyone in this server, as if they just pulled that seed (any rarity; the real threshold is Legendary). Packs made by owner commands never announce.'},
 {'/test announce global <seed> [here] @username','R151: publish it to the other servers (this server is the origin and shows nothing; add here to also see the other-server chat line).'},
 {'/test announce record [bestpull|biggestfruit] [seed] @username','R151: the record chat line ("took BEST PULL TODAY!") for the hub displays.'},

 {'— GIFTS —',''},
 {'/test gifts @username','Gifts this player sent that are still finishing.'},
 {'/test gifts recover @username','Finish stuck gifts now (normally automatic within a minute).'},

 {'— HUB DISPLAYS (R151) —',''},
 {'/test bestpull FirePepperSeed @username','A test BEST PULL TODAY for that player: a seed id or plant name (fire pepper), at its odds in its biome\'s Pack03. Shows on this server only; add share to write it to the shared board too.'},
 {'/test bigfruit 12.4 @username','A test BIGGEST FRUIT TODAY: a fruit of today\'s type weighing that many kg (gold or diamond for a coat, share to write the shared board). Shows on this server only unless shared.'},
 {'/test hubdisplays','server: Both corner displays: the day, the fruit of the day, the champions and where they came from, the shared board\'s health and the part counts. hubdisplays reset empties both boards (this server and the shared one); hubdisplays day +1 previews tomorrow\'s fruit on this server (day 0 comes back).'},

 {'— VERITY\'S VOICE —',''},
 {'/test verityvoice 2.1 0.3','server: Find where "Hello, my name is Verity" ends by ear. verityvoice <end seconds> [start seconds] sets the cut for this server and plays it for you at once (from anywhere); verityvoice alone plays it again and prints the numbers; verityvoice reset goes back to VerityConfig. Copy the final numbers into VerityConfig.GreetingStart / GreetingEnd.'},

 {'— CHECKS & SETTINGS —',''},
 {'/test economy','server: Upgrade prices, fruit value range and cash cap.'},
 {'/test mechshop','server: Mech pack prices and product setup.'},
 {'/test voidcheck','Check the Void Pack odds add up. Grants nothing.'},
 {'/test collisions','server: Re-apply walk-through decorations.'},
 {'/test perf','Toggle the performance display.'},
 {'/test effects low','Plant effects: normal, low or off.'},
}
