"""R156: the owner's Classic Pyramid (docs/proposals/R156/pyramid/classic_pyramid_parts.json, read from his .rbxm by tools/rbxm_parts.py) as a Luau table for the
tests, straight from his file (not from PyramidRules156): every part, bottom to top, its size, centre, colour, material, shape and anchoring.
Usage: python3 owner_slabs.py <classic_pyramid_parts.json> <out owner_slabs.luau>"""
import json
import sys

MATERIALS = {820: 'Limestone', 256: 'Plastic', 272: 'SmoothPlastic'}
SHAPES = {0: 'Ball', 1: 'Block', 2: 'Cylinder'}
d = json.load(open(sys.argv[1]))
models = [p for p in d if p['ClassName'] == 'Model']
parts = sorted((p for p in d if p['ClassName'] == 'Part'), key=lambda p: p['CFrame']['pos'][1])
assert len(models) == 1 and all(p['parent'] == models[0]['ref'] for p in parts), 'one model holding every part'
colors = {tuple(p['Color3uint8']) for p in parts}
mats = {p['Material'] for p in parts}
shapes = {p['shape'] for p in parts}
assert len(colors) == 1 and len(mats) == 1 and len(shapes) == 1, 'one colour, one material, one shape'
assert all(p['Anchored'] and p['CFrame']['rot'] == [1, 0, 0, 0, 1, 0, 0, 0, 1] and p['Transparency'] == 0 for p in parts), 'anchored, upright, opaque'
rows = ['{SX=%r,SY=%r,SZ=%r,X=%r,Y=%r,Z=%r}' % (p['size'][0], p['size'][1], p['size'][2], *p['CFrame']['pos']) for p in parts]
color = next(iter(colors))
mat = next(iter(mats))
out = ('-- generated by owner_slabs.py from the owner\'s Classic Pyramid (asset 113814131474028, classic_pyramid_parts.json)\n'
       + 'return {Model=%r,Slabs={%s},Color={%d,%d,%d},Material=%d,MaterialName=%r,Shape=%r}\n'
       % (models[0]['Name'], ',\n '.join(rows), color[0], color[1], color[2], mat, MATERIALS[mat], SHAPES[next(iter(shapes))]))
open(sys.argv[2], 'w').write(out)
print('%d slabs, colour %s, material %s' % (len(parts), color, MATERIALS[mat]))
