"""R158 bats: write BatSwingPose158.luau (the PROPOSED swing, same API as src/ReplicatedStorage/BatSwingPose.lua) from solve_keys158.py's keys.
Usage: python3 make_pose158.py keys158.json > BatSwingPose158.luau
"""
import json, sys

def wrap(a):
    a = ((a + 180) % 360) - 180
    return 180 if a == -180 else a

def ang(v):
    return 'a(%d,%d,%d)' % tuple(wrap(int(round(x))) for x in v)

keys = json.load(open(sys.argv[1]))
r15, r6 = keys['R15'], keys['R6']
names15 = ['RightShoulder', 'RightElbow', 'RightWrist', 'LeftShoulder', 'LeftElbow', 'Waist']
lines = []
lines.append('--!nocheck')
lines.append('-- R158 PROPOSAL (preview, NOT in src/): the new bat swing. Same API as src/ReplicatedStorage/BatSwingPose.lua (Sample(name,time,lead,isR6) ->')
lines.append('-- parent-space joint CFrame, weight), so BatClient would only swap the module. Timed on the reference video (see animation.md):')
lines.append('--   load .00-.07 (fast) -> coil .07-.22 (slow drift, the "hold") -> strike .22-.30 (accelerating; the bat sweeps from behind the head round')
lines.append('--   the right side) -> CONTACT .30 (bat straight ahead at hip height = today\'s server Windup) -> through .30-.335 (bat out to the left) ->')
lines.append('--   follow-through .335-.52 (wraps low to the left, slowing: the weight) -> hold .52-.60 -> recovery .60-.85 (rises in front, blends back into')
lines.append('--   the tool hold). Upper body only: right arm, left arm, waist (R6: the whole-body RootJoint at 60 % twist, no lean, its own one-piece arm).')
lines.append('-- Keys: generated by make_pose158.py from solve_keys158.py (an IK fit of where the bat should be, on an approximate blocky rig).')
lines.append('local P={Total=.85,Contact=.30,HitFrom=.24,HitTo=.36,TrailFrom=.21,TrailTo=.40}')
lines.append('local function a(x,y,z)return CFrame.Angles(math.rad(x),math.rad(y),math.rad(z))end')
lines.append('-- key order: ' + ' '.join('%s %.3f' % (k['Key'], k['Time']) for k in r15))
lines.append('local poses={')
for n in names15:
    lines.append(' %s={%s},' % (n, ','.join(ang(k[n]) for k in r15)))
lines.append('}')
lines.append('local r6={')
lines.append(' RightShoulder={%s},' % ','.join(ang(k['RightShoulder']) for k in r6))
lines.append(' LeftShoulder={%s},' % ','.join(ang(k['LeftShoulder']) for k in r6))
lines.append(' Waist={%s},' % ','.join(ang(k['RootJoint']) for k in r6))
lines.append('}')
lines.append('''local function smooth(t)t=math.clamp(t,0,1);return t*t*(3-2*t)end
local function outQuad(t)t=math.clamp(t,0,1);return 1-(1-t)*(1-t)end
local function outCubic(t)t=math.clamp(t,0,1);return 1-(1-t)^3 end
-- lead: seconds of the swing that passed before this client first saw it (the load restarts from there, as today)
function P.Sample(name,time,lead,isR6)
 if name=='RootJoint'then name='Waist'end
 local k=(isR6 and r6 or poses)[name];if not k then return CFrame.new(),0 end
 if time<0 or time>=P.Total then return CFrame.new(),0 end
 local A,A2,B,C,D,E,F=k[1],k[2],k[3],k[4],k[5],k[6],k[7]
 if time<.07 then
  local start=math.clamp(tonumber(lead)or 0,0,.07*.6)
  return A,outQuad((time-start)/(.07-start))                -- load: fast out of the tool hold
 end
 if time<.22 then return A:Lerp(A2,smooth((time-.07)/.15)),1 end -- coil: a slow drift, never a frozen hold
 if time<.30 then
  local s=((time-.22)/.08)^2                                 -- strike: accelerating, fastest at contact; B at .26 (s = .25)
  if s<.25 then return A2:Lerp(B,s/.25),1 end
  return B:Lerp(C,(s-.25)/.75),1
 end
 if time<.335 then return C:Lerp(D,(time-.30)/.035),1 end    -- through: still fast, the bat goes out to the left
 if time<.52 then return D:Lerp(E,outCubic((time-.335)/.185)),1 end -- follow-through: slows down (the weight)
 if time<.60 then return E,1 end
 if time<.72 then return E:Lerp(F,smooth((time-.60)/.12)),1 end -- recovery: the bat rises in front
 return F,1-smooth((time-.72)/(P.Total-.72))                   -- and blends back into the tool hold
end
return P''')
print('\n'.join(lines))
