"""R151 chip-bag shape variations, designed in Blender (bpy 4.5, Cycles CPU).

Owner: "make pack shape variations in blender; the pack shape will still be a chip shape but will be slightly different".

What this does
  1. Defines the six variation FIELDS (the same maths as src/ReplicatedStorage/PackShapes151.lua: Field / Scales). A field is a smooth map over the pouch's
     NORMALISED box (u, v, w = x, y, z of the pack-local box, each -1..1): u' = u * sx(u,v,w), w' = w * sz(u,v,w), v' = v. y never moves and the crimps
     (|v| >= .94: where the seal and the 8 tear strips sit) are untouched, so the pivot, the bottom line, the seal and the strips stay exactly where they are.
     Nothing grows by more than 5%.
  2. --samples: writes docs/proposals/R151/tests/pack_shape_samples.luau, the field evaluated on a lattice. tests/test_pack_shapes.luau compares Luau's Field
     with these numbers, so the Blender design and the game cannot drift apart (change one side and the test fails).
  3. Builds a parametric chip-bag stand-in on the standard pouch footprint (1.97 x 2.06 studs, ~1.0 deep, pillowy body, flat serrated crimps top and bottom),
     deforms it with each field and renders a comparison sheet: TODAY next to the six variations, front / side / three-quarter (Cycles on the CPU, a
     translucent ghost of today's bag behind every variation, the seal and the eight tear strips drawn in place). The print is a checker texture on the
     bag's ORIGINAL (u, v), so it visibly follows the deformation: this is why the shipped version deforms the real meshes (their vertex-colour prints survive).

Usage (the bpy in the shared venv; run it from a directory that has no bisect.py / random.py next to it):
  .../bpyenv/bin/python docs/proposals/R151/blender/pack_shapes.py [--out docs/proposals/R151/pack_shapes.png] [--samples-only] [--width 2800]
"""
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..', '..', '..'))

NAMES = ['Pillow', 'Hourglass', 'Pear', 'Top-heavy', 'Shoulders', 'Flat']
COUNT = 6


# ---- the fields (keep in step with PackShapes151.lua: the Luau test compares them) -------------------------------------------------------------------
def clamp01(x):
    return 0.0 if x < 0 else 1.0 if x > 1 else x


def ss(a, b, x):
    t = clamp01((x - a) / (b - a))
    return t * t * (3 - 2 * t)


def bump(x, c, s):
    d = (x - c) / s
    return math.exp(-d * d)


def body(v):
    return 1 - ss(.80, .94, abs(v))


def shoulder(v):
    return ss(.45, .80, abs(v)) * body(v)


def scales(i, u, v, w):
    """(sx, sz) of variation i (1..6) at (u, v, w)."""
    if i == 1:   # Pillow: puffier, a little narrower
        b = body(v) * (1 - v * v)
        return 1 - .04 * b, 1 + .05 * b
    if i == 2:   # Hourglass: slimmer waist
        b = body(v)
        return 1 - .09 * b * bump(v, 0, .5), 1 + .03 * b * bump(v, 0, .6)
    if i == 3:   # Pear: fuller at the bottom
        g = body(v) * v
        return 1 - .05 * g, 1 - .03 * g
    if i == 4:   # Top-heavy: fuller at the top
        g = body(v) * v
        return 1 + .05 * g, 1 + .03 * g
    if i == 5:   # Shoulders: the corners below each crimp rounded off
        return 1 - .08 * ss(.45, .85, abs(u)) * shoulder(v), 1.0
    if i == 6:   # Flat: a flatter belly
        b = body(v)
        return 1 + .02 * b * (1 - v * v), 1 - .15 * b * bump(v, 0, .75) * (1 - .3 * u * u)
    raise ValueError(i)


def field(i, u, v, w):
    sx, sz = scales(i, u, v, w)
    return u * sx, v, w * sz


def write_samples(path):
    us = [-1, -.8, -.45, 0, .3, .7, 1]
    vs = [-1, -.95, -.9, -.7, -.4, 0, .25, .6, .85, .94, 1]
    ws = [-1, 0, .6]
    rows = []
    for i in range(1, COUNT + 1):
        for u in us:
            for v in vs:
                for w in ws:
                    a, b, c = field(i, u, v, w)
                    rows.append((i, u, v, w, a, b, c))
    with open(path, 'w', encoding='utf-8') as f:
        f.write('--!nocheck\n-- GENERATED by docs/proposals/R151/blender/pack_shapes.py (--samples-only): the Blender design\'s fields evaluated on a lattice,\n'
                '-- {variation, u, v, w, u2, v2, w2}. test_pack_shapes.luau checks PackShapes151.Field against every row.\nreturn{\n')
        for r in rows:
            f.write('{%d,%s},\n' % (r[0], ','.join('%.12g' % x for x in r[1:])))
        f.write('}\n')
    return len(rows)


def amplitude():
    """The largest outward / inward scale of each variation over a fine lattice (the 5% promise)."""
    out = {}
    for i in range(1, COUNT + 1):
        hi_x = hi_z = -9.0
        lo_x = lo_z = 9.0
        for a in range(-100, 101):
            for b in range(-100, 101):
                u, v = a / 100.0, b / 100.0
                sx, sz = scales(i, u, v, 0)
                hi_x, lo_x, hi_z, lo_z = max(hi_x, sx), min(lo_x, sx), max(hi_z, sz), min(lo_z, sz)
        out[i] = (lo_x, hi_x, lo_z, hi_z)
    return out


# ---- the stand-in bag ---------------------------------------------------------------------------------------------------------------------------------
# Pack-local box of the standard pouch (Storm_02): 1.97 wide, 2.06 tall, ~1.0 deep.
CENTER = (0.0, -0.01, 0.0)
HALF = (0.985, 1.03, 0.5)
NU, NV = 96, 128


def thickness(u, v):
    """w of the FRONT surface at (u, v) in the normalised box (the back is -w): a pillow body, thin serrated crimps, closed at the seams."""
    side = (1 - abs(u) ** 2.4) ** 0.6 if abs(u) < 1 else 0.0
    core = 1 - 0.9 * ss(.50, .94, abs(v))                       # the body fades to the flat crimp
    ripple = 1 + 0.18 * math.sin(2 * math.pi * 17 * (u + 1) / 2) * ss(.90, .96, abs(v))
    closing = 1 - ss(.985, 1.0, abs(v))                         # the two faces meet on the top / bottom edge
    return side * core * ripple * closing


def bag_geometry(i):
    """Vertices (x, y, z in studs), faces and uvs of the stand-in, variation i (0 = today's)."""
    verts, uvs, faces = [], [], []
    front = {}
    back = {}
    for jv in range(NV + 1):
        v = -1 + 2 * jv / NV
        for iu in range(NU + 1):
            u = -1 + 2 * iu / NU
            t = thickness(u, v)
            for sign, table in ((1, front), (-1, back)):
                if sign == -1 and t == 0.0:
                    table[(iu, jv)] = front[(iu, jv)]
                    continue
                uu, vv, ww = (u, v, sign * t) if i == 0 else field(i, u, v, sign * t)
                table[(iu, jv)] = len(verts)
                verts.append((CENTER[0] + uu * HALF[0], CENTER[1] + vv * HALF[1], CENTER[2] + ww * HALF[2]))
                uvs.append(((u + 1) / 2, (v + 1) / 2))
    for jv in range(NV):
        for iu in range(NU):
            a, b, c, d = (iu, jv), (iu + 1, jv), (iu + 1, jv + 1), (iu, jv + 1)
            faces.append((front[a], front[b], front[c], front[d]))
            faces.append((back[d], back[c], back[b], back[a]))
    return verts, faces, uvs


def render_sheet(out, width):
    import bpy
    import bmesh
    from mathutils import Vector

    bpy.ops.wm.read_factory_settings(use_empty=True)
    scene = bpy.context.scene
    scene.render.engine = 'CYCLES'
    scene.cycles.device = 'CPU'
    scene.cycles.samples = 40
    scene.cycles.use_denoising = True
    try:
        scene.cycles.denoiser = 'OPENIMAGEDENOISE'
    except Exception:
        pass
    scene.view_settings.view_transform = 'Standard'
    scene.view_settings.look = 'None'
    scene.render.film_transparent = False
    world = bpy.data.worlds.new('w')
    scene.world = world
    world.use_nodes = True
    bg = world.node_tree.nodes['Background']
    bg.inputs['Color'].default_value = (0.93, 0.93, 0.92, 1)
    bg.inputs['Strength'].default_value = 0.9

    def mat(name, color, rough=0.5, metal=0.0, emission=None):
        m = bpy.data.materials.new(name)
        m.use_nodes = True
        b = m.node_tree.nodes['Principled BSDF']
        b.inputs['Base Color'].default_value = color
        b.inputs['Roughness'].default_value = rough
        b.inputs['Metallic'].default_value = metal
        if emission is not None:
            b.inputs['Emission Color'].default_value = emission
            b.inputs['Emission Strength'].default_value = 1.0
        return m

    # the print: a checker on the bag's ORIGINAL (u, v) (so it follows the deformation) with a darker band at each crimp
    bag_mat = bpy.data.materials.new('bag')
    bag_mat.use_nodes = True
    nt = bag_mat.node_tree
    for n in list(nt.nodes):
        if n.type != 'OUTPUT_MATERIAL':
            nt.nodes.remove(n)
    out_node = [n for n in nt.nodes if n.type == 'OUTPUT_MATERIAL'][0]
    bsdf = nt.nodes.new('ShaderNodeBsdfPrincipled')
    bsdf.inputs['Roughness'].default_value = 0.34
    bsdf.inputs['Metallic'].default_value = 0.25
    texco = nt.nodes.new('ShaderNodeTexCoord')
    mapping = nt.nodes.new('ShaderNodeMapping')
    mapping.inputs['Scale'].default_value = (6, 9, 1)
    checker = nt.nodes.new('ShaderNodeTexChecker')
    checker.inputs['Color1'].default_value = (0.96, 0.66, 0.10, 1)
    checker.inputs['Color2'].default_value = (0.88, 0.45, 0.07, 1)
    sep = nt.nodes.new('ShaderNodeSeparateXYZ')
    band = nt.nodes.new('ShaderNodeMath')
    band.operation = 'GREATER_THAN'
    band.inputs[1].default_value = 0.0
    ramp = nt.nodes.new('ShaderNodeMapRange')
    mixc = nt.nodes.new('ShaderNodeMix')
    mixc.data_type = 'RGBA'
    mixc.inputs['B'].default_value = (0.20, 0.13, 0.05, 1)
    nt.links.new(texco.outputs['UV'], mapping.inputs['Vector'])
    nt.links.new(mapping.outputs['Vector'], checker.inputs['Vector'])
    nt.links.new(texco.outputs['UV'], sep.inputs['Vector'])
    # |v-.5|*2 > .94 -> crimp band
    absn = nt.nodes.new('ShaderNodeMath')
    absn.operation = 'SUBTRACT'
    absn.inputs[1].default_value = 0.5
    abs2 = nt.nodes.new('ShaderNodeMath')
    abs2.operation = 'ABSOLUTE'
    mul2 = nt.nodes.new('ShaderNodeMath')
    mul2.operation = 'MULTIPLY'
    mul2.inputs[1].default_value = 2.0
    gt = nt.nodes.new('ShaderNodeMath')
    gt.operation = 'GREATER_THAN'
    gt.inputs[1].default_value = 0.935
    nt.links.new(sep.outputs['Y'], absn.inputs[0])
    nt.links.new(absn.outputs['Value'], abs2.inputs[0])
    nt.links.new(abs2.outputs['Value'], mul2.inputs[0])
    nt.links.new(mul2.outputs['Value'], gt.inputs[0])
    nt.links.new(gt.outputs['Value'], mixc.inputs['Factor'])
    nt.links.new(checker.outputs['Color'], mixc.inputs['A'])
    nt.links.new(mixc.outputs['Result'], bsdf.inputs['Base Color'])
    nt.links.new(bsdf.outputs['BSDF'], out_node.inputs['Surface'])

    ghost_mat = bpy.data.materials.new('ghost')
    ghost_mat.use_nodes = True
    gt_nodes = ghost_mat.node_tree
    for n in list(gt_nodes.nodes):
        if n.type != 'OUTPUT_MATERIAL':
            gt_nodes.nodes.remove(n)
    gout = [n for n in gt_nodes.nodes if n.type == 'OUTPUT_MATERIAL'][0]
    gdiff = gt_nodes.nodes.new('ShaderNodeEmission')
    gdiff.inputs['Color'].default_value = (0.25, 0.28, 0.35, 1)
    gtr = gt_nodes.nodes.new('ShaderNodeBsdfTransparent')
    gmix = gt_nodes.nodes.new('ShaderNodeMixShader')
    gmix.inputs['Fac'].default_value = 0.28
    gt_nodes.links.new(gtr.outputs['BSDF'], gmix.inputs[1])
    gt_nodes.links.new(gdiff.outputs['Emission'], gmix.inputs[2])
    gt_nodes.links.new(gmix.outputs['Shader'], gout.inputs['Surface'])

    seal_mat = mat('seal', (0.10, 0.22, 0.30, 1), rough=0.5)
    text_mat = mat('text', (0.08, 0.08, 0.10, 1), rough=1.0)
    rule_mat = mat('rule', (0.75, 0.75, 0.74, 1), rough=1.0)

    def make_mesh(name, i, material):
        verts, faces, uvs = bag_geometry(i)
        me = bpy.data.meshes.new(name)
        me.from_pydata(verts, [], faces)
        me.update()
        uv = me.uv_layers.new(name='UVMap')
        for poly in me.polygons:
            for li in poly.loop_indices:
                uv.data[li].uv = uvs[me.loops[li].vertex_index]
        for p in me.polygons:
            p.use_smooth = True
        me.materials.append(material)
        ob = bpy.data.objects.new(name, me)
        scene.collection.objects.link(ob)
        return ob

    def box(name, size, loc, material, parent):
        me = bpy.data.meshes.new(name)
        bm = bmesh.new()
        bmesh.ops.create_cube(bm, size=1.0)
        bm.to_mesh(me)
        bm.free()
        ob = bpy.data.objects.new(name, me)
        ob.scale = size
        ob.location = loc
        ob.data.materials.append(material)
        scene.collection.objects.link(ob)
        ob.parent = parent
        return ob

    def text(body_text, loc, size, align='CENTER'):
        curve = bpy.data.curves.new('t', 'FONT')
        curve.body = body_text
        curve.size = size
        curve.align_x = align
        curve.align_y = 'CENTER'
        ob = bpy.data.objects.new('t', curve)
        ob.location = loc
        ob.data.materials.append(text_mat)
        scene.collection.objects.link(ob)
        return ob

    cols = list(range(0, COUNT + 1))               # 0 = today's shape
    pitch_x = 2.55
    rows = [('FRONT', 0.0, 0.0), ('SIDE', 90.0, 0.0), ('3/4 VIEW', 38.0, -14.0)]   # (label, yaw about Y, pitch about X) in degrees
    pitch_y = 2.95
    x0 = 0.0
    top = 0.0
    left_margin = 1.9
    cache = {}
    for ri, (label, yaw, pitch) in enumerate(rows):
        cy = top - 1.9 - ri * pitch_y
        text(label, (x0 - left_margin - 0.35, cy, 0), 0.20, align='LEFT')
        for ci, i in enumerate(cols):
            cx = x0 + ci * pitch_x
            holder = bpy.data.objects.new('h', None)
            scene.collection.objects.link(holder)
            holder.location = (cx, cy, 0)
            holder.rotation_mode = 'YXZ'
            holder.rotation_euler = (math.radians(pitch), math.radians(yaw), 0)
            bag = make_mesh('bag%d_%d' % (i, ri), i, bag_mat)
            bag.parent = holder
            if i != 0:
                # today's bag, in the same pose, a little behind (along the camera axis), so the change can be read off
                behind = bpy.data.objects.new('hb', None)
                scene.collection.objects.link(behind)
                behind.location = (cx, cy, -0.9)
                behind.rotation_mode = 'YXZ'
                behind.rotation_euler = holder.rotation_euler
                ghost = make_mesh('ghost%d_%d' % (i, ri), 0, ghost_mat)
                ghost.parent = behind
            # the seal and the 8 tear strips of the ordinary pack, where the game puts them (root plane, y = -1.12 / 1.11)
            box('seal', (1.9, 0.16, 0.035), (0, -1.12, 0), seal_mat, holder)
            for s in range(1, 9):
                box('strip%d' % s, (1.9 / 8 + .001, 0.18, 0.035), (-1.9 / 2 + (s - .5) * 1.9 / 8, 1.11, 0), seal_mat, holder)
            if ri == 0:
                label2 = 'TODAY' if i == 0 else '%d  %s' % (i, NAMES[i - 1])
                text(label2, (cx, top - 0.35, 0), 0.19)
    sheet_w = x0 + (len(cols) - 1) * pitch_x + 1.5 - (x0 - left_margin - 0.5)
    sheet_h = 0.9 + len(rows) * pitch_y + 0.55
    text('R151 chip-bag shape variations  -  the shape of every design is TODAY\'s mesh moved by one of these six fields (ghost = today); seal and tear strips drawn in place',
         (x0 - left_margin - 0.35, top - 0.95 - len(rows) * pitch_y + 0.05 - 0.15, 0), 0.115, align='LEFT')
    cam_data = bpy.data.cameras.new('cam')
    cam_data.type = 'ORTHO'
    cam_data.ortho_scale = sheet_w
    cam = bpy.data.objects.new('cam', cam_data)
    cam.location = ((x0 - left_margin - 0.5 + x0 + (len(cols) - 1) * pitch_x + 1.5) / 2, top - sheet_h / 2 + 0.1, 20)
    cam.rotation_euler = (0, 0, 0)
    scene.collection.objects.link(cam)
    scene.camera = cam
    scene.render.resolution_x = width
    scene.render.resolution_y = int(width * sheet_h / sheet_w)
    scene.render.resolution_percentage = 100
    scene.render.image_settings.file_format = 'PNG'
    scene.render.filepath = out
    for name, loc, energy, size in (('key', (-6, 10, 14), 900, 12), ('fill', (14, 4, 10), 350, 14), ('rim', (0, -8, 12), 250, 10)):
        ld = bpy.data.lights.new(name, 'AREA')
        ld.energy = energy
        ld.size = size
        lo = bpy.data.objects.new(name, ld)
        lo.location = (cam.location.x + loc[0], cam.location.y + loc[1], loc[2])
        direction = Vector((cam.location.x, cam.location.y, 0)) - lo.location
        lo.rotation_euler = direction.to_track_quat('-Z', 'Y').to_euler()
        scene.collection.objects.link(lo)
    bpy.ops.render.render(write_still=True)


def main(argv):
    out = os.path.join(REPO, 'docs', 'proposals', 'R151', 'pack_shapes.png')
    width = 2800
    samples = os.path.join(REPO, 'docs', 'proposals', 'R151', 'tests', 'pack_shape_samples.luau')
    i = 0
    while i < len(argv):
        if argv[i] == '--out':
            out = argv[i + 1]
            i += 1
        elif argv[i] == '--width':
            width = int(argv[i + 1])
            i += 1
        elif argv[i] == '--samples-out':
            samples = argv[i + 1]
            i += 1
        i += 1
    n = write_samples(samples)
    print('samples: %d rows -> %s' % (n, samples))
    for k, (lx, hx, lz, hz) in amplitude().items():
        print('variation %d %-10s x scale %.3f..%.3f, z scale %.3f..%.3f' % (k, NAMES[k - 1], lx, hx, lz, hz))
    if '--samples-only' in argv:
        return
    render_sheet(out, width)
    print('sheet ->', out)


if __name__ == '__main__':
    main(sys.argv[1:])
