"""R153 jitter (owner: "reduce jitter in effects"): SpeedGainPopup.client.lua with the R153 jitter edits put back as they were, for the suites that hold
the script to an earlier version (R151 run_speed_popups.sh: the belt arrows' sha; R151 run_treadmills.sh: the popup half as at its base).
The two edits: the popup field hangs on the HumanoidRootPart at the head's height (was the Head, which bobs with the treadmill run); the belt
arrows move every frame on a near belt in view (were a 1/30 or 1/20 s tick). Each must be found exactly once, or the run stops.
Usage: python3 undo_jitter153.py <SpeedGainPopup.client.lua> <out>"""
import sys
EDITS = [  # (now, as it was)
 ('-- R153 (owner: "reduce jitter in effects"): the field hangs on the HumanoidRootPart at the head\'s height (StudsOffsetWorldSpace), not on the Head:\n-- the head bobs with the treadmill run and the whole fan shook with it. (No root: the head, as before.)\nlocal function takeField(head)\n\tlocal field = table.remove(freeFields)\n\twhile field and field.Gui.Parent ~= playerGui do field = table.remove(freeFields) end -- one that was removed from the PlayerGui is not reused\n\tfield = field or makeField()\n\tlocal root = head.Parent and head.Parent:FindFirstChild("HumanoidRootPart")\n\tfield.Gui.Adornee = root or head\n\tfield.Gui.StudsOffsetWorldSpace = root and Vector3.new(0, head.Position.Y - root.Position.Y, 0) or Vector3.zero\n',
  'local function takeField(head)\n\tlocal field = table.remove(freeFields)\n\twhile field and field.Gui.Parent ~= playerGui do field = table.remove(freeFields) end -- one that was removed from the PlayerGui is not reused\n\tfield = field or makeField()\n\tfield.Gui.Adornee = head\n'),
 ('    local low=player:GetAttribute(\'FastMode\')==true\n    -- R153 (owner: "reduce jitter in effects"): a near belt in view moves its arrows every frame (they stepped at 30 / 20 Hz); out of view the old tick,\n    -- with the time each belt is owed (the arrows are where they would have been). The view test is TreadmillFx.Visible\'s generous cone.\n    local tick=elapsed>=(low and 1/20 or 1/30);if tick then elapsed=0 end\n    local camera=workspace.CurrentCamera;local view=camera and camera.CFrame;table.clear(moving);table.clear(frames)\n    for belt,record in pairs(belts)do\n        if not belt:IsDescendantOf(workspace)or record.Art.Parent~=belt.Parent then\n            releaseBelt(record);belts[belt]=nil\n        else\n            local offset=view and belt.Position-view.Position\n            local distance=offset and offset.Magnitude or math.huge\n            local near=distance<(low and 90 or 140)\n            if tick then for _,e in ipairs(record.Emitters)do\n                if e.Parent then\n                    local enabled=not low and distance<85\n                    if e.Enabled~=enabled then e.Enabled=enabled end\n                end\n            end end\n            record.Owed=near and(record.Owed or 0)+dt or 0\n            if near and(tick or distance<28 or view.LookVector:Dot(offset/distance)>.25)then\n                local step=math.min(record.Owed,.10);record.Owed=0\n',
  "    local low=player:GetAttribute('FastMode')==true\n    if elapsed<(low and 1/20 or 1/30)then return end\n    local step=math.min(elapsed,.10);elapsed=0\n    local camera=workspace.CurrentCamera;table.clear(moving);table.clear(frames)\n    for belt,record in pairs(belts)do\n        if not belt:IsDescendantOf(workspace)or record.Art.Parent~=belt.Parent then\n            releaseBelt(record);belts[belt]=nil\n        else\n            local distance=camera and (camera.CFrame.Position-belt.Position).Magnitude or math.huge\n            local near=distance<(low and 90 or 140)\n            for _,e in ipairs(record.Emitters)do\n                if e.Parent then\n                    local enabled=not low and distance<85\n                    if e.Enabled~=enabled then e.Enabled=enabled end\n                end\n            end\n            if near then\n"),
]
text = open(sys.argv[1], encoding='utf-8').read()
for now, was in EDITS:
    if text.count(now) != 1:
        sys.exit('undo_jitter153: an R153 jitter edit is not found exactly once: ' + now.split('\n')[0][:80])
    text = text.replace(now, was)
open(sys.argv[2], 'w', encoding='utf-8').write(text)
