"""Usage: python3 gen_pack_templates.py <place.rbxl> [out.luau]   (default out: ../tests/pack_templates.luau)

Reads the REAL pack templates (ReplicatedStorage/SeedPackMeshAssets: 42 Models, one per biome x design, each with its MeshParts,
their Size / Material / MeshId and the PackLocalFrame attribute SeedPackRenderer.BuildStandard places them with) out of a place file with
the R149 reader (docs/proposals/R149/tools/rbxl_geom.py -> tools/rbxl.py) and writes them as a Luau data module for the Roblox mock:
    return function(W) ... end    -- replaces the stand-in fixtures.packAssets with the real templates

Read-only on the place. Only the template geometry is read: the meshes themselves are uploaded assets (MeshId), their vertices and vertex
colours are not in the place file and cannot be downloaded offline, so tests / previews treat each MeshPart as its Size box."""
import os, sys, collections
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', '..', 'R149', 'tools'))
import rbxl_geom as G  # noqa: E402

place = sys.argv[1]
out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(HERE, '..', 'tests', 'pack_templates.luau')
inst, parent = G.load(place)
kids = collections.defaultdict(list)
for c, p in parent.items():
    kids[p].append(c)
names = {r: G.text(i.get('Name', b'?')) for r, i in inst.items()}


def path_of(r):
    o = []
    while r in inst:
        o.append(names[r]); r = parent.get(r, -1)
    return '/'.join(reversed(o))


folder = [r for r in inst if path_of(r) == 'ReplicatedStorage/SeedPackMeshAssets'][0]
fattr = G.attributes(inst[folder].get('AttributesSerialize', b''))
models = []
for m in sorted(kids[folder], key=lambda r: names[r]):
    a = G.attributes(inst[m].get('AttributesSerialize', b''))
    parts = []
    for p in sorted(kids[m], key=lambda r: names[r]):
        i = inst[p]
        assert i['ClassName'] == 'MeshPart', (names[m], names[p], i['ClassName'])
        pa = G.attributes(i.get('AttributesSerialize', b''))
        (pos, rot) = pa['PackLocalFrame']['CFrame']
        size = i.get('size') or i.get('Size')
        parts.append(dict(name=names[p], size=size, pos=pos, rot=rot, mat=G.MATERIALS.get(i.get('Material'), 'Plastic'),
                          mesh=G.text(i.get('MeshId', b'')), tex=G.text(i.get('TextureID', b'')), color=i.get('Color3uint8', (255, 255, 255)),
                          t=i.get('Transparency', 0.0)))
    models.append((names[m], a, parts))


def f(v):
    return '%.7g' % v


lines = ['--!nocheck',
         '-- GENERATED by docs/proposals/R151/tools/gen_pack_templates.py from the owner\'s place file (ReplicatedStorage/SeedPackMeshAssets): the REAL',
         '-- pack templates (%d designs, %d MeshParts; MeshId, Size, Material, PackLocalFrame). The meshes themselves are uploaded assets whose vertices' % (len(models), sum(len(p) for _, _, p in models)),
         '-- (and vertex-colour print) are not in the place file: tests treat every MeshPart as its Size box. Do not edit by hand.',
         'local D={']
for name, a, parts in models:
    lines.append(' {%s,{' % ('"%s"' % name))
    for p in parts:
        lines.append('  {n="%s",s={%s,%s,%s},p={%s,%s,%s},r={%s},m="%s",id="%s",c={%d,%d,%d}%s},' % (
            p['name'], f(p['size'][0]), f(p['size'][1]), f(p['size'][2]), f(p['pos'][0]), f(p['pos'][1]), f(p['pos'][2]),
            ','.join(f(v) for row in p['rot'] for v in row), p['mat'], p['mesh'], *p['color'], (',tx="%s"' % p['tex']) if p['tex'] else ''))
    lines.append(' }},')
lines += ['}', 'return function(W)', ' local R=W.R;local folder=W.RS:FindFirstChild(\'SeedPackMeshAssets\')',
          ' if folder then folder:Destroy()end',
          ' folder=R.new(\'Folder\');folder.Name=\'SeedPackMeshAssets\'',
          ' for k,v in pairs({CatalogDigest=%s,ImportFixVersion=%s,MeshBakeVersion=%s,OrientationFixVersion=%s,Ready=true}) do folder:SetAttribute(k,v) end' % (
              '"%s"' % fattr.get('CatalogDigest', ''), int(fattr.get('ImportFixVersion', 1)), int(fattr.get('MeshBakeVersion', 123)), int(fattr.get('OrientationFixVersion', 2))),
          ' for _,d in ipairs(D) do',
          '  local m=R.new(\'Model\');m.Name=d[1];m:SetAttribute(\'MeshBakeVersion\',123)',
          '  for _,s in ipairs(d[2]) do',
          '   local p=R.new(\'MeshPart\');p.Name=s.n;p.Size=R.Vector3.new(s.s[1],s.s[2],s.s[3]);p.Color=R.Color3.fromRGB(s.c[1],s.c[2],s.c[3])',
          '   p.Material=R.Enum.Material[s.m];p.MeshId=s.id;p.TextureID=s.tx or\'\';p.Anchored=true;p.CanCollide=false;p.CastShadow=false',
          '   local frame=R.CFrame.new(s.p[1],s.p[2],s.p[3],table.unpack(s.r));p.CFrame=frame;p:SetAttribute(\'PackLocalFrame\',frame);p.Parent=m',
          '  end',
          '  m:SetAttribute(\'MeshCount\',#d[2]);m.Parent=folder',
          ' end',
          ' folder.Parent=W.RS',
          ' return D',
          'end']
open(out, 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
print('wrote', out, len(models), 'templates')
